name: Delete All Packages

on:
  push:
    branches:
      - delete_packages  # Chỉ kích hoạt khi branch delete_packages được push

jobs:
  delete-all-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get list of all packages
        id: get_packages
        run: |
          PACKAGES_JSON=$(curl -H "Authorization: token ${{ secrets.GH_DESTRUCTION_TOKEN }}" \
                              -H "Accept: application/vnd.github.v3+json" \
                              "https://api.github.com/orgs/KryptonReborn/packages?package_type=maven&per_page=100")
          echo "::set-output name=packages::$(echo "$PACKAGES_JSON" | jq -c '[.[] | .name]')"

      - name: Delete all packages
        run: |
          PACKAGES=$(echo '${{ steps.get_packages.outputs.packages }}' | jq -r '.[]')
          for PACKAGE in $PACKAGES; do
            echo "Deleting entire package: $PACKAGE"
            curl -X DELETE -H "Authorization: token ${{ secrets.GH_DESTRUCTION_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "https://api.github.com/orgs/KryptonReborn/packages/maven/$PACKAGE"
          done
        env:
          GH_DESTRUCTION_TOKEN: ${{ secrets.GH_DESTRUCTION_TOKEN }}